$(document).ready(function() {
    $("#btn-1").click(function() {
        $("#house").show();
        $("#dubstep").hide();
        $("#techno").hide();
        $("#trance").hide();
        $("#EDM").hide();
        $("#harcore").hide();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
    $("#btn-2").click(function() {
        $("#house").hide();
        $("#dubstep").show();
        $("#techno").hide();
        $("#trance").hide();
        $("#EDM").hide();
        $("#harcore").hide();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
    $("#btn-3").click(function() {
        $("#house").hide();
        $("#dubstep").hide();
        $("#techno").show();
        $("#trance").hide();
        $("#EDM").hide();
        $("#harcore").hide();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
    $("#btn-4").click(function() {
        $("#house").hide();
        $("#dubstep").hide();
        $("#techno").hide();
        $("#trance").show();
        $("#EDM").hide();
        $("#harcore").hide();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
    $("#btn-5").click(function() {
        $("#house").hide();
        $("#dubstep").hide();
        $("#techno").hide();
        $("#trance").hide();
        $("#EDM").show();
        $("#harcore").hide();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
    $("#btn-6").click(function() {
        $("#house").hide();
        $("#dubstep").hide();
        $("#techno").hide();
        $("#trance").hide();
        $("#EDM").hide();
        $("#harcore").show();

        h1.pause();
        iconh1.src = "images/play.png";
        h2.pause();
        iconh2.src = "images/play.png";
        h3.pause();
        iconh3.src = "images/play.png";
        h4.pause();
        iconh4.src = "images/play.png";
        h5.pause();
        iconh5.src = "images/play.png";
        h6.pause();
        iconh6.src = "images/play.png";
        h7.pause();
        iconh7.src = "images/play.png";
        h8.pause();
        iconh8.src = "images/play.png";
        h9.pause();
        iconh9.src = "images/play.png";
        h10.pause();
        iconh10.src = "images/play.png";
        h11.pause();
        iconh11.src = "images/play.png";
        h12.pause();
        iconh12.src = "images/play.png";
        h13.pause();
        iconh13.src = "images/play.png";
        h14.pause();
        iconh14.src = "images/play.png";
        h15.pause();
        iconh15.src = "images/play.png";
        h16.pause();
        iconh16.src = "images/play.png";
        h17.pause();
        iconh17.src = "images/play.png";
        h18.pause();
        iconh18.src = "images/play.png";
        h19.pause();
        iconh19.src = "images/play.png";
        h20.pause();
        iconh20.src = "images/play.png";

        d1.pause();
        icond1.src = "images/play.png";
        d2.pause();
        icond2.src = "images/play.png";
        d3.pause();
        icond3.src = "images/play.png";
        d4.pause();
        icond4.src = "images/play.png";
        d5.pause();
        icond5.src = "images/play.png";
        d6.pause();
        icond6.src = "images/play.png";
        d7.pause();
        icond7.src = "images/play.png";
        d8.pause();
        icond8.src = "images/play.png";
        d9.pause();
        icond9.src = "images/play.png";
        d10.pause();
        icond10.src = "images/play.png";
        d11.pause();
        icond11.src = "images/play.png";
        d12.pause();
        icond12.src = "images/play.png";
        d13.pause();
        icond13.src = "images/play.png";
        d14.pause();
        icond14.src = "images/play.png";
        d15.pause();
        icond15.src = "images/play.png";
        d16.pause();
        icond16.src = "images/play.png";
        d17.pause();
        icond17.src = "images/play.png";
        d18.pause();
        icond18.src = "images/play.png";
        d19.pause();
        icond19.src = "images/play.png";
        d20.pause();
        icond20.src = "images/play.png";

        e1.pause();
        icone1.src = "images/play.png";
        e2.pause();
        icone2.src = "images/play.png";
        e3.pause();
        icone3.src = "images/play.png";
        e4.pause();
        icone4.src = "images/play.png";
        e5.pause();
        icone5.src = "images/play.png";
        e6.pause();
        icone6.src = "images/play.png";
        e7.pause();
        icone7.src = "images/play.png";
        e8.pause();
        icone8.src = "images/play.png";
        e9.pause();
        icone9.src = "images/play.png";
        e10.pause();
        icone10.src = "images/play.png";
        e11.pause();
        icone11.src = "images/play.png";
        e12.pause();
        icone12.src = "images/play.png";
        e13.pause();
        icone13.src = "images/play.png";
        e14.pause();
        icone14.src = "images/play.png";
        e15.pause();
        icone15.src = "images/play.png";
        e16.pause();
        icone16.src = "images/play.png";
        e17.pause();
        icone17.src = "images/play.png";
        e18.pause();
        icone18.src = "images/play.png";
        e19.pause();
        icone19.src = "images/play.png";
        e20.pause();
        icone20.src = "images/play.png";

        hr1.pause();
        iconhr1.src = "images/play.png";
        hr2.pause();
        iconhr2.src = "images/play.png";
        hr3.pause();
        iconhr3.src = "images/play.png";
        hr4.pause();
        iconhr4.src = "images/play.png";
        hr5.pause();
        iconhr5.src = "images/play.png";
        hr6.pause();
        iconhr6.src = "images/play.png";
        hr7.pause();
        iconhr7.src = "images/play.png";
        hr8.pause();
        iconhr8.src = "images/play.png";
        hr9.pause();
        iconhr9.src = "images/play.png";
        hr10.pause();
        iconhr10.src = "images/play.png";
        hr11.pause();
        iconhr11.src = "images/play.png";
        hr12.pause();
        iconhr12.src = "images/play.png";
        hr13.pause();
        iconhr13.src = "images/play.png";
        hr14.pause();
        iconhr14.src = "images/play.png";
        hr15.pause();
        iconhr15.src = "images/play.png";
        hr16.pause();
        iconhr16.src = "images/play.png";
        hr17.pause();
        iconhr17.src = "images/play.png";
        hr18.pause();
        iconhr18.src = "images/play.png";
        hr19.pause();
        iconhr19.src = "images/play.png";
        hr20.pause();
        iconhr20.src = "images/play.png";

        tr1.pause();
        icontr1.src = "images/play.png";
        tr2.pause();
        icontr2.src = "images/play.png";
        tr3.pause();
        icontr3.src = "images/play.png";
        tr4.pause();
        icontr4.src = "images/play.png";
        tr5.pause();
        icontr5.src = "images/play.png";
        tr6.pause();
        icontr6.src = "images/play.png";
        tr7.pause();
        icontr7.src = "images/play.png";
        tr8.pause();
        icontr8.src = "images/play.png";
        tr9.pause();
        icontr9.src = "images/play.png";
        tr10.pause();
        icontr10.src = "images/play.png";
        tr11.pause();
        icontr11.src = "images/play.png";
        tr12.pause();
        icontr12.src = "images/play.png";
        tr13.pause();
        icontr13.src = "images/play.png";
        tr14.pause();
        icontr14.src = "images/play.png";
        tr15.pause();
        icontr15.src = "images/play.png";
        tr16.pause();
        icontr16.src = "images/play.png";
        tr17.pause();
        icontr17.src = "images/play.png";
        tr18.pause();
        icontr18.src = "images/play.png";
        tr19.pause();
        icontr19.src = "images/play.png";
        tr20.pause();
        icontr20.src = "images/play.png";

        t1.pause();
        icont1.src = "images/play.png";
        t2.pause();
        icont2.src = "images/play.png";
        t3.pause();
        icont3.src = "images/play.png";
        t4.pause();
        icont4.src = "images/play.png";
        t5.pause();
        icont5.src = "images/play.png";
        t6.pause();
        icont6.src = "images/play.png";
        t7.pause();
        icont7.src = "images/play.png";
        t8.pause();
        icont8.src = "images/play.png";
        t9.pause();
        icont9.src = "images/play.png";
        t10.pause();
        icont10.src = "images/play.png";
        t11.pause();
        icont11.src = "images/play.png";
        t12.pause();
        icont12.src = "images/play.png";
        t13.pause();
        icont13.src = "images/play.png";
        t14.pause();
        icont14.src = "images/play.png";
        t15.pause();
        icont15.src = "images/play.png";
        t16.pause();
        icont16.src = "images/play.png";
        t17.pause();
        icont17.src = "images/play.png";
        t18.pause();
        icont18.src = "images/play.png";
        t19.pause();
        icont19.src = "images/play.png";
        t20.pause();
        icont20.src = "images/play.png";
    })
})